image: kkarczmarczyk/node-yarn:latest 

before_script:
    - yarn install

stages:
    - lint
    - test

eslint: 
    stage: lint
    script: 
        - yarn lint

jest:
    stage: test
    script:
        - yarn test
