
variables:
    GRADLE_USER_HOME: $CI_PROJECT_DIR/.gradle

stages:
  - test
  - build

# test:
#     stage: test
#     image: node:alpine
#     before_script:
#         - yarn install
#     script:
#         - yarn lint:ci
#         - yarn jest

build-android:
    stage: build
    image: reactnativecommunity/react-native-android:latest
    cache:
      key: gradle cache
      paths:
          - .gradle/wrapper/
          - .gradle/caches/
    before_script:
        - echo ${SENTRY_PROPS} | base64 -d > android/sentry.properties
        - echo ${PROD_ENV} | base64 -d > .env
        - yarn install
    script:
        # - android/gradlew --scan --no-daemon ":app:assemble"
        - android/gradlew build --debug 
    artifacts:
        paths:
            - android/app/build/outputs/apk/debug/app-debug.apk
            - android/app/build/outputs/apk/release/app-release-unsigned.apk
            - android/app/build/outputs/apk/release/app-release.apk
