image: node:latest 

cache:
    key: "$CI_BUILD_NAME"
    paths:
        - node_modules/
        - .cache/
        - latest.tar.gz

before_script:
    - wget -N https://yarnpkg.com/latest.tar.gz
    - tar zxf latest.tar.gz
    - mv dist /opt/
    - export PATH="/opt/dist/bin:$PATH"
    - yarn config set cache-folder .cache
    - yarn install

stages:
    - lint
    - test

eslint: 
    stage: lint
    script: 
        - yarn lint

jest:
    stage: test
    script:
        - yarn test
