image: wkuipers/docker-react-native-yarn:latest

before_script:
    - yarn install

stages:
    - lint
    - build

eslint:
    stage: lint
    script:
        - yarn run eslint *.js app

build_android:
    stage: build
    script:
        - cd android
        - ./gradlew build
