image: wkuipers/docker-react-native-yarn:latest

variables:
    GRADLE_USER_HOME: $CI_PROJECT_DIR/.gradle

cache:
    key: $CI_PROJECT_NAME
    paths:
        - .gradle/wrapper/
        - .gradle/caches/

before_script:
    - yarn install

stages:
    - lint
    - build

eslint:
    stage: lint
    script:
        - yarn run eslint *.js app

build_android:
    stage: build
    script:
        - cd android
        - ./gradlew build
