image: node:6

variables:
    GRADLE_USER_HOME: $CI_PROJECT_DIR/.gradle

cache:
    key: $CI_PROJECT_NAME
    paths:
        - .gradle/wrapper/
        - .gradle/caches/

before_script:
    - yarn install

stages:
    - lint

eslint:
    stage: lint
    script:
        - yarn ci-lint
