image: kkarczmarczyk/node-yarn:latest

stages:
    - test

cache:
    untracked: true
    key: "$CI_PROJECT_ID"
    paths:
        - node_modules/
        - .yarn

yarn install:
    stage: test
    script:
        - yarn config set cache-folder .yarn
        - yarn install
        - yarn lint
