image: node:8-alpine

variables:
    GRADLE_USER_HOME: $CI_PROJECT_DIR/.gradle

stages:
  - dependencies
  - validate
  - build

yarn dependencies:
    stage: dependencies
    cache:
        key: $CI_JOB_NAME
        paths:
            - $ARTIFACTS_PATH
            - $TOOL_CACHE_PATH
    artifacts:
        expire_in: 1 hour
        paths:
            - $ARTIFACTS_PATH
    script:
        - yarn install --lockfile-only
    variables:
        TOOL_CACHE_PATH: /usr/local/share/.cache/yarn/v1
        ARTIFACTS_PATH: node_modules

eslint:
    stage: validate
    script:
        - yarn lint:ci

jest:
    stage: validate
    script:
        - yarn jest

# We don't need this step as long as there are no tests for the native Android code
# test android:
#     stage: validate
#     script:
#         - cd $CI_PROJECT_DIR/android/
#         - gradle --no-daemon --continue ":app:testDebugUnitTest" ":app:testReleaseUnitTest"
#     cache:
#         key: $CI_JOB_NAME
#         paths:
#             - .gradle/wrapper/
#             - .gradle/caches/
#     artifacts:
#         expire_in: 1 hour
#         paths:
#             - .gradle/wrapper/
#             - .gradle/caches/

build android:
    image: thalia/android-react-native:latest
    stage: build
    cache:
      key: gradle cache
      paths:
          - $CI_PROJECT_DIR/.gradle/wrapper/
          - $CI_PROJECT_DIR/.gradle/caches/
    before_script:
        - set +o pipefail
        - yes | /opt/android-sdk-linux/tools/bin/sdkmanager --licenses
        - set -o pipefail
    script:
        - echo $SENTRY_PROPS | base64 -d > ./android/sentry.properties
        - echo $PROD_ENV | base64 -d > .env
        - cd $CI_PROJECT_DIR/android/
        - ./gradlew --no-daemon ":app:assemble"
    artifacts:
        paths:
            - $CI_PROJECT_DIR/android/app/build/outputs/apk/debug/app-debug.apk
            - $CI_PROJECT_DIR/android/app/build/outputs/apk/release/app-release-unsigned.apk
            - $CI_PROJECT_DIR/android/app/build/outputs/apk/release/app-release.apk